server:
  port: 18088

spring:
  application:
    name: springboot-jpa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/jpa_test?userUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: Root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
#        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 0
    password: root
  jackson:
    time-zone: GMT+8


logging:
  level:
    root: info
    com.example.yyw: debug
    org.springframework.data.jpa: debug
  file: D:\\yw\\logs\\${spring.application.name}.log
  file.max-size: 100MB
  file.max-history: 60
