server:
  port: 18081

spring:
  application:
    name: springboot-mybatis
  datasource:
    ssm:
      poolName: ${spring.application.name}
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://139.199.179.164:3306/ssm?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: Root123
      autoCommit: false
      minIdle: 5
      maximumPoolSize: 20
      connectionInitSql: select 1
      hikari:
        idle-timeout: 10000

mybatis:
  configuration:
    # 	是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
#  mapper-locations:

mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  #设置 insert 和 update 中，是否判断字符串类型!=”
  not-empty: true

logging:
  level:
    root: info
    com.example.yyw: debug
  file: ${spring.application.name}

student:
  name: 'hahhah'
  age: 12