server:
  port: 8989
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 2
    password: root

#redisson:
#  threads: 10
#  nettyThreads: 10
#  codec: org.redisson.codec.JsonJacksonCodec
#  useLinuxNativeEpoll: false
#  singleServerConfig:
#    idleConnectionTimeout: 10000
#    pingTimeout: 1000
#    connectTimeout: 10000
#    timeout: 3000
#    retryAttempts: 3
#    retryInterval: 1500
#    reconnectionTimeout: 3000
#    failedAttempts: 3
#    password: root
#    subscriptionsPerConnection: 5
#    clientName: null
#    address: "redis://127.0.0.1:6379"
#    subscriptionConnectionMinimumIdleSize: 1
#    subscriptionConnectionPoolSize: 50
#    connectionMinimumIdleSize: 10
#    connectionPoolSize: 64
#    database: 3
#    dnsMonitoring: false
#    dnsMonitoringInterval: 5000