server:
  port: 18093

spring:
  application:
    name: springboot-elasticsearch
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.245.130:9300
#      properties:
#        path:
#          home: /yw/wwwroot/elasticsearch
#        transport:
#          tcp:
#            connect_timeout: 120s

logging:
  level:
    root: info
    com.example.yyw: debug
    org.springframework.data.elasticsearch: debug
  file: D:\\yw\\logs\\${spring.application.name}.log
  file.max-size: 100MB
  file.max-history: 60