server:
  port: 19001
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 虚拟空间地址
    virtual-host: yyw-rabbitmq
    # 配置发布消息确认回调
    publisher-confirms: true
    publisher-returns: true
