spring:
  security:
    user:
      name: "admin"
      password: "admin"

# \u5728admin-server\u5DE5\u7684\u914D\u7F6E\u6587\u4EF6application.yml\u4E2D\u914D\u7F6Espring security\u7684\u7528\u6237\u540D\u548C\u5BC6\u7801\uFF0C\u8FD9\u65F6\u9700\u8981\u5728\u670D\u52A1\u6CE8\u518C\u65F6\u5E26\u4E0Ametadata-map\u7684\u4FE1\u606F
#eureka:
#  instance:
#    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}
  mail:
    host: smtp.qq.com
    username: 2507967396@qq.com
    password: kziktiflnzjiecbc
  boot:
    admin:
      notify:
        mail:
          to: 2507967396@qq.com
          from: 2507967396@qq.com